runmode: debug               # 开发模式, debug, release, test
addr: :9090                  # HTTP绑定端口
name: restful                # API Server的名字
url: http://127.0.0.1:9090   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数尝试的次数
jwt_secret: eyJpYXQiOjE1MjgwMTY5MjIsImlkIjowLCJuYmY #jwt Token Signature 签名秘钥
log:
  writers: file,stdout
  logger_level: DEBUG      # 日志级别，DEBUG、INFO、WARN、ERROR、FATAL
  logger_file: log/apiserver.log # 日志文件
  log_format_text: false
  rollingPolicy: size # 这里将日志转存策略设置为 size，转存大小设置为 1 MB
  log_rotate_date: 1  #
  log_rotate_size: 1
  log_backup_count: 7  #当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数
db:
  name: restful
  addr: 127.0.0.1:3306
  username: root
  password: root
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: root